CREATE ROLE admin WITH LOGIN PASSWORD 'admin123';
CREATE ROLE manager WITH LOGIN PASSWORD 'manager123' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE metrics_db;
GRANT ALL PRIVILEGES ON DATABASE metrics_db TO superman ;
GRANT ALL PRIVILEGES ON DATABASE metrics_db TO super;
