global:
  scrape_interval: 15s

# tag::adocPrometheus[]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'workers'
    static_configs:
      - targets: ['host.docker.internal:8082']
# end::adocPrometheus[]